### ISSUE TITLE
Two minor issues

### ISSUE THREAD

**Issue by HansOlsson** [BigMautone/Drones#1]
I just looked at the library from stackoverflow and found that:

- The `velocityCap `function uses `maxSpeed` instead of `K.maxSpeed` in some cases.
- The functions use `InputReal `and `OutputReal ` components, but functions may currently not contain connector components: https://specification.modelica.org/master/functions.html#function-as-a-specialized-class

**Comment by BigMautone** [comment]
Thank you Hans, i checked and now i corrected it!

Il mar 1 feb 2022, 16:13 Hans Olsson ***@***.***> ha scritto:
